version: '3.8'

services:
  # MySQL 데이터베이스
  mysql:
    image: mysql:8.0
    container_name: finmate-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: finmate_db
      MYSQL_USER: finmate
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: >
      --default-authentication-plugin=mysql_native_password
      --skip-name-resolve
      --bind-address=0.0.0.0
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone='+09:00'
      --innodb-buffer-pool-size=256M
      --max-connections=200
    networks:
      - finmate-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "finmate", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # phpMyAdmin (DB 관리용)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: finmate-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: finmate
      PMA_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root1234
      UPLOAD_LIMIT: 100M
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - finmate-network

  # Redis (캐시용) - 선택사항
  redis:
    image: redis:7-alpine
    container_name: finmate-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass finmate123
    volumes:
      - redis_data:/data
    networks:
      - finmate-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  finmate-network:
    driver: bridge