name: "🚀 기능 개발 (Feature Implementation)"
description: "FinMate 제테크 서비스의 새로운 기능 개발 요청"
title: "[FEAT] "
labels: ["feature", "enhancement"]
assignees: ["mango606"]

body:
  - type: markdown
    attributes:
      value: |
        ## 🏦 FinMate 기능 개발 요청
        
        새로 구현할 기능의 목표와 세부 작업 내용을 명확하게 정리해주세요.
        제테크 금융 서비스의 사용자 경험 향상을 위한 기능을 제안해주세요.

  - type: dropdown
    id: feature-category
    attributes:
      label: "📋 기능 카테고리"
      description: "개발할 기능이 속하는 카테고리를 선택해주세요"
      options:
        - "🔐 회원/인증 (Member & Auth)"
        - "💰 금융 프로필 (Financial Profile)"
        - "🎯 금융 목표 관리 (Goal Management)"
        - "📊 투자 포트폴리오 (Investment Portfolio)"
        - "📈 거래 내역 관리 (Transaction)"
        - "🎓 금융 교육 (Education)"
        - "📱 알림/커뮤니케이션 (Notification)"
        - "🔧 시스템/인프라 (Infrastructure)"
        - "📊 분석/리포트 (Analytics)"
        - "🔍 기타 (Others)"
    validations:
      required: true

  - type: textarea
    id: feature-goal
    attributes:
      label: "🎯 기능 목표 (Goal)"
      description: "이 기능을 통해 달성하고자 하는 최종 목표를 구체적으로 설명해주세요"
      placeholder: |
        예시: 사용자가 월별 투자 목표를 설정하고 진행률을 실시간으로 추적할 수 있어서, 
        체계적인 자산 관리와 목표 달성을 통한 제테크 성공률을 높일 수 있다.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "✅ 완료 조건 (Acceptance Criteria)"
      description: "어떤 조건이 충족되면 이 기능이 완성된 것으로 볼 수 있는지 구체적인 시나리오로 정의해주세요"
      placeholder: |
        - 사용자는 투자 목표 설정 페이지에서 목표 금액과 기간을 입력할 수 있다
        - 목표 진행률이 실시간으로 계산되어 대시보드에 표시된다
        - 목표 달성률이 50%, 80%, 100%에 도달할 때 알림이 발송된다
        - 목표 수정 및 삭제가 가능하며, 이력이 기록된다
        - 월별/연별 목표 달성 통계를 차트로 확인할 수 있다
    validations:
      required: true

  - type: checkboxes
    id: todo-list
    attributes:
      label: "🛠️ 세부 작업 목록 (To-Do List)"
      description: "기능을 완성하기 위해 필요한 세부 개발 작업을 체크리스트로 작성해주세요"
      options:
        - label: "📋 API: 새로운 API 엔드포인트 설계 및 구현"
        - label: "🗄️ DB: 데이터베이스 스키마 설계 및 테이블 생성"
        - label: "🔧 Service: 비즈니스 로직 구현"
        - label: "🎨 DTO: 요청/응답 데이터 모델 정의"
        - label: "🔐 Security: 권한 및 보안 검증 로직"
        - label: "📊 Validation: 입력값 유효성 검증"
        - label: "🧪 Test: 단위 테스트 및 통합 테스트 작성"
        - label: "📖 Docs: API 문서 업데이트 (Swagger)"
        - label: "🎯 Frontend: 프론트엔드 연동 가이드 작성"

  - type: dropdown
    id: priority
    attributes:
      label: "🚨 우선순위"
      description: "이 기능의 개발 우선순위를 선택해주세요"
      options:
        - "🔥 High (긴급) - 핵심 기능, 즉시 개발 필요"
        - "⚡ Medium (보통) - 중요 기능, 다음 스프린트"
        - "💡 Low (낮음) - 개선 기능, 여유 있을 때"
    validations:
      required: true

  - type: textarea
    id: business-impact
    attributes:
      label: "📈 비즈니스 임팩트"
      description: "이 기능이 FinMate 서비스와 사용자에게 미칠 긍정적 영향을 설명해주세요"
      placeholder: |
        예시:
        - 사용자 목표 달성률 20% 향상 예상
        - 앱 사용 빈도 증가로 유저 리텐션 개선
        - 체계적인 자산 관리 도구 제공으로 서비스 차별화
        - 금융 목표 달성 성공 사례를 통한 마케팅 효과

  - type: textarea
    id: technical-considerations
    attributes:
      label: "⚙️ 기술적 고려사항"
      description: "구현 시 고려해야 할 기술적 요소나 제약사항이 있다면 작성해주세요"
      placeholder: |
        예시:
        - 실시간 데이터 업데이트를 위한 WebSocket 연동 검토
        - 대용량 거래 데이터 처리를 위한 배치 처리 최적화
        - 외부 금융 API 연동 시 보안 및 안정성 확보
        - 기존 데이터와의 호환성 및 마이그레이션 계획

  - type: checkboxes
    id: related-features
    attributes:
      label: "🔗 연관 기능"
      description: "이 기능과 연관된 기존 기능이나 동시에 개발되어야 할 기능을 선택해주세요"
      options:
        - label: "👤 회원 관리 시스템"
        - label: "🔐 JWT 인증 시스템"
        - label: "💰 금융 프로필 관리"
        - label: "🎯 금융 목표 설정"
        - label: "📊 투자 포트폴리오"
        - label: "📈 거래 내역 추적"
        - label: "🎓 금융 교육 콘텐츠"
        - label: "📱 알림 시스템"
        - label: "📊 대시보드 및 통계"

  - type: textarea
    id: mockup-reference
    attributes:
      label: "🎨 UI/UX 참고자료"
      description: "관련 화면 설계나 참고할 만한 UI/UX가 있다면 링크나 설명을 적어주세요"
      placeholder: |
        예시:
        - Figma 디자인: https://figma.com/...
        - 참고 앱: 토스, 뱅크샐러드의 목표 설정 기능
        - 와이어프레임: (이미지 첨부 또는 간단한 텍스트 설명)

  - type: checkboxes
    id: final-checklist
    attributes:
      label: "📋 최종 확인"
      options:
        - label: "관련된 기존 이슈가 없는 것을 확인했습니다"
          required: true
        - label: "이 기능이 FinMate의 제테크 서비스 목표에 부합함을 확인했습니다"
          required: true
        - label: "기술적 실현 가능성을 검토했습니다"
          required: true