name: "버그 수정 (Bug Fix)"
description: "발견한 버그를 분석하고 수정 계획을 세웁니다."
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "버그의 원인을 분석하고 수정 계획을 명확하게 정리합니다."

  - type: textarea
    id: bug-symptom
    attributes:
      label: "1. 버그 현상 및 재현 방법"
      description: "어떤 현상이 발생하는지, 어떻게 재현할 수 있는지 순서대로 작성해주세요."
      placeholder: |
        - 현상: 특정 API 호출 시 500 에러 발생
        - 재현: GET /api/users/123 요청 시 NullPointerException 발생
    validations:
      required: true

  - type: textarea
    id: root-cause
    attributes:
      label: "2. 원인 분석 (Root Cause Analysis)"
      description: "로그나 코드를 분석하여 버그의 근본 원인이 무엇인지 작성해주세요."
      placeholder: "예: 사용자 조회 시 연관된 데이터가 null일 경우를 처리하지 못함."
    validations:
      required: true

  - type: checkboxes
    id: todo-list
    attributes:
      label: "3. 수정 계획 (To-Do List)"
      description: "버그를 해결하기 위한 구체적인 작업 목록을 작성해주세요."
      options:
        - label: "Service 로직: null 체크 로직 추가"
        - label: "Test: 해당 케이스에 대한 단위 테스트 코드 추가"
        - label: "Docs: 변경된 내용 API 문서에 반영"

  - type: dropdown
    id: severity
    attributes:
      label: "4. 중요도 (Severity)"
      description: "버그의 영향도를 선택해주세요."
      options:
        - "High: 기능 마비, 데이터 손실"
        - "Medium: 기능 오동작"
        - "Low: 사소한 오류"
    validations:
      required: true